import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

import Tab from 'react-bootstrap/Tab';
import Tabs from 'react-bootstrap/Tabs';
import Form from 'react-bootstrap/Form'


export default function Home() {
  return (
    <div className={styles.container}>
     
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className={styles.c1}>
      <Row>
        <Col md={3} sm={12}>
        <div className={styles.c2}>
        <Row>
        
          <Col md={4} sm={12}>
            <div >
              <h2 className={styles.h2}>P</h2>
              
            </div>
          </Col>
          <Col md={8} sm={12}>
            <div>
              <p>
              <h4 className={styles.x}>Pushpendra 27 </h4></p>
              <p className={styles.test}>Get Acccess information and interect with fellow auto lovers</p>
              
                <p className="styles.box2">
                  <Image src="/pic2.jpg" alt="pic1" width="45px" height="25px" />
                  <span>Newbie</span>
                 </p>
                  
                  <div className={styles.edit121}>
                    <p> joined in july 2022 </p>
                    <p className={styles.edit122}>Edit</p>
                  </div>
              
              </div>
              
              
          </Col>
          <Col md={12} sm={12}>
          
            <div className={styles.edit120}>
              <h4 className={styles.x}>My Garage </h4>
              <p className={styles.edit123}>Add/Edit</p>
              </div>
              
              <p className={styles.test}>&#9679; Maruti Suzuki Swift 2014-2022</p>
              
             
            
          </Col>
          <Col md={4} sm={12}>
            <div>
              <img src="/1.png" width="100%" height="100%"/>
              
            </div>
          </Col>
          <Col md={8} sm={12}>
            <div>
          
              
              <p className={styles.test}>Help Fellow auto lovers by review and answering Question & become a zigwheels legend </p>
              
               
              
    
              </div>
          </Col>
          
        </Row>
        </div>
        </Col>
        <Col md={9} sm={12}>
          
        <div>
          <h3>My Activity</h3>
         
          
        <p>
        
        <Tabs
      defaultActiveKey="profile"
      id="fill-tab-example"
      className={styles.tab_nav}
      fill>
    
      <Tab eventKey="home" title="Question For You">
        <Form>
      <Form.Group className="mb-3">
      <div>
        <p><span className={styles.ans}>Lavkush </span>asked about Maruti Suzuki Swift 2014-2021</p>
      </div>
      <h6 classname="styles.h3">Q. This car CNG variant or not-Swift? </h6>
        <Form.Control placeholder="Add your answer"  />
        <p className={styles.ans5}>Add 4 More Answer<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-compact-down" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M1.553 6.776a.5.5 0 0 1 .67-.223L8 9.44l5.776-2.888a.5.5 0 1 1 .448.894l-6 3a.5.5 0 0 1-.448 0l-6-3a.5.5 0 0 1-.223-.67z"/>
</svg></p>
      </Form.Group>
      </Form>
      
      
      <Form>
      <Form.Group className="mb-3">
      
      <div>
        <p><span className={styles.ans}>Lavkush </span>asked about Maruti Suzuki Swift 2014-2021</p>
      </div>
        <h6 classname="styles.h3">Q. This car CNG variant or not-Swift? </h6>
        <Form.Control placeholder="Add your answer"  />
        <p className={styles.ans5}>Add 4 More Answer<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-compact-down" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M1.553 6.776a.5.5 0 0 1 .67-.223L8 9.44l5.776-2.888a.5.5 0 1 1 .448.894l-6 3a.5.5 0 0 1-.448 0l-6-3a.5.5 0 0 1-.223-.67z"/>
</svg></p>
      </Form.Group>
      </Form>
      
      <Form>
      <Form.Group className="mb-3">
      <div>
        <p><span className={styles.ans}>Lavkush </span>asked about Maruti Suzuki Swift 2014-2021</p>
      </div>
      <h6 classname="styles.h3">Q. This car CNG variant or not-Swift? </h6>
        <Form.Control placeholder="Add your answer" />
        <p className={styles.ans5}>Add 4 More Answer<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-compact-down" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M1.553 6.776a.5.5 0 0 1 .67-.223L8 9.44l5.776-2.888a.5.5 0 1 1 .448.894l-6 3a.5.5 0 0 1-.448 0l-6-3a.5.5 0 0 1-.223-.67z"/>
</svg></p>
      </Form.Group>
      </Form>

      <Form>
      <Form.Group className="mb-3">
      <div>
        <p><span className={styles.ans}>Lavkush </span>asked about Maruti Suzuki Swift 2014-2021</p>
      </div>
      <h6 classname="styles.h3">Q. This car CNG variant or not-Swift? </h6>
        <Form.Control placeholder="Add your answer"  />
        
        </Form.Group>
        </Form>
        <p className={styles.ans5}> <span>Add 4 More Answer</span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-compact-down" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M1.553 6.776a.5.5 0 0 1 .67-.223L8 9.44l5.776-2.888a.5.5 0 1 1 .448.894l-6 3a.5.5 0 0 1-.448 0l-6-3a.5.5 0 0 1-.223-.67z"/>
</svg></p>
      
        <Form>
      <Form.Group className="mb-3" controlId="formBasicEmail">
      <div>
        <p><span className={styles.ans}>Lavkush </span>asked about Maruti Suzuki Swift 2014-2021</p>
      </div>
      
      <h6 classname="styles.h3">Q. This car CNG variant or not-Swift? </h6>
        <Form.Control className="styles.form_box" type="text" placeholder="Add your answert" />
        <p className={styles.ans5}>Add 4 More Answer<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-compact-down" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M1.553 6.776a.5.5 0 0 1 .67-.223L8 9.44l5.776-2.888a.5.5 0 1 1 .448.894l-6 3a.5.5 0 0 1-.448 0l-6-3a.5.5 0 0 1-.223-.67z"/>
</svg></p>
        
      </Form.Group>
      </Form>
      </Tab>


      <Tab eventKey="profile" title="Answer">
       <div>
        <p><span className={styles.ans}>Prabhat </span>asked about Royal Enfield 350 (2014-2021) </p>
      </div>
      <Row>
          
          <Col md={12} sm={12}>
      <h6 classname="styles.h3">Q. What's the minimum height of a person required to drive classic 350 ? </h6>
      <div className={styles.ans1}><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
              <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
            </svg>
        Follow Question
        <span className={styles.line}>|</span>
        <div>
           <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">
              <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
            </svg>  Add Answer
        </div>
        </div></Col>
        </Row>
        <div>
        <Row>
          
        <Col md={1} sm={12}>
            <div>
              <h2 className={styles.anp}>P</h2>
              
            </div>
            
          </Col>
          <Col md={11} sm={12}>
          <div>
          <p><span className={styles.php}>Pushpendra </span> |1 month ago </p>
            </div>
            <div className={styles.ans2}>
           
              <div className={styles.ans3}>
                @Jatav | are you mad bro if ffer are ridding bullet with one or two guy..being let not touch the you are gone a suffer to much .. 
                if there will be some holes like dig on road ..you are gone ..5.b is enough ..Read more  

              </div>
              Hi
            </div>
            <div className={styles.ans6}><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" 
               class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                  </svg>  0  Reply</div>
                  <p className={styles.ans5}>Add 3 More Answer<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-compact-down" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1.553 6.776a.5.5 0 0 1 .67-.223L8 9.44l5.776-2.888a.5.5 0 1 1 .448.894l-6 3a.5.5 0 0 1-.448 0l-6-3a.5.5 0 0 1-.223-.67z"/>
                      </svg></p>
            </Col>
        </Row>

      </div>
      <div>
        <p><span className={styles.ans}>Prabhat </span>asked about Royal Enfield 350 (2014-2021) </p>
      </div>
      <Row>
          
          <Col md={12} sm={12}>
      <h6 classname="styles.h3">Q. How is the suspension ? </h6>
      <div className={styles.ans1}><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
              <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
            </svg>
        Follow Question
        <span className={styles.line}>|</span>
        <div>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">
              <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
            </svg>  Add Answer
        </div>
        </div></Col>
        </Row>
        <div>
        <Row>
          
        <Col md={1} sm={12}>
            <div>
              <h2 className={styles.anp}>P</h2>
              
            </div>
            
          </Col>
          <Col md={11} sm={12}>
          <div>
          <p><span className={styles.php}>Pushpendra </span> |1 month ago </p>
            </div>
            <div className={styles.ans2}>
           
              <div className={styles.ans3}>
                @Jatav | are you mad bro if ffer are ridding bullet with one or two guy..being let not touch the you are gone a suffer to much .. 
                if there will be some holes like dig on road ..you are gone ..5.b is enough ..Read more  

              </div>
              Hi
            </div>
            <div className={styles.ans6}><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" 
               class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                  </svg>  0  Reply</div>
                  <p className={styles.ans5}>Add 3 More Answer<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-compact-down" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M1.553 6.776a.5.5 0 0 1 .67-.223L8 9.44l5.776-2.888a.5.5 0 1 1 .448.894l-6 3a.5.5 0 0 1-.448 0l-6-3a.5.5 0 0 1-.223-.67z"/>
                    </svg></p>
               
            </Col>
        </Row>

      </div>
      <div>
        <p><span className={styles.ans}>Prabhat </span>asked about Royal Enfield 350 (2014-2021) </p>
      </div>
      <Row>
          
          <Col md={12} sm={12}>
      <h6 classname="styles.h3">Q. What's the minimum height of a person required to drive classic 350 ? </h6>
      <div className={styles.ans1}><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
              <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
            </svg>
        Follow Question
        <span className={styles.line}>|</span>
        <div>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">
              <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
            </svg>  Add Answer
        </div>
        </div></Col>
        </Row>
        <div>
        <Row>
          
        <Col md={1} sm={12}>
            <div>
              <h2 className={styles.anp}>P</h2>
              
            </div>
            
          </Col>
          <Col md={11} sm={12}>
          <div>
            <p><span className={styles.php}>Pushpendra </span> |1 month ago </p>
            </div>
            <div className={styles.ans2}>
           
              <div className={styles.ans3}>
                @Jatav | are you mad bro if ffer are ridding bullet with one or two guy..being let not touch the you are gone a suffer to much .. 
                if there will be some holes like dig on road ..you are gone ..5.b is enough ..Read more  

              </div>
              Hi
            </div>
            <div className={styles.ans6}><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" 
               class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                  </svg>  0  Reply</div>
                  <p className={styles.ans5}>Add 3 More Answer<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-compact-down" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M1.553 6.776a.5.5 0 0 1 .67-.223L8 9.44l5.776-2.888a.5.5 0 1 1 .448.894l-6 3a.5.5 0 0 1-.448 0l-6-3a.5.5 0 0 1-.223-.67z"/>
                    </svg></p>
            </Col>
        </Row>

      </div>
      </Tab>
      <Tab eventKey="longer-tab" title="Question Asked">
       
      </Tab>
      <Tab eventKey="contact" title="Question Followed">
        <div>
        <p><span className={styles.qfollow}>Plabon  </span>asked about hyundai Venue 2019-2022</p>
        </div>
        <Row>
          
          <Col md={12} sm={12}>
           <h6 classname="styles.h3">Q. Shooulld i go for Hyundai Venue S 1.2 L variant or Ford 
           Freestyle Titanium,as both come in near about similar price range? Will I miss out too much in the Venue's variant?</h6>
            <div className={styles.qfollow1}><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
              <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
            </svg>
              UnFollow Question
              <span className={styles.line}>|</span>  
          <div>
            
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">
              <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
            </svg>    Add Answer
        </div>
        
        </div>
        <Form.Control placeholder="Add your answer" />
        </Col>
        </Row>
        <div></div>
       
      </Tab>
      <Tab eventKey="home" title="Your Reviews">
        
      </Tab>
      <Tab eventKey="home" title="Shortlist">
        
      </Tab>
    </Tabs>
        </p>


        </div>
        </Col>
        </Row>
    </Container>
    

      <main className={styles.main}>
        
        </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
