import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home3.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Accordion from 'react-bootstrap/Accordion';
import Tab from 'react-bootstrap/Tab';
import Tabs from 'react-bootstrap/Tabs';
import Form from 'react-bootstrap/Form';
import Button from 'react-bootstrap/Button';
import React, {useState} from 'react';

import axios from 'axios';
import Carousel from "react-multi-carousel";
import "react-multi-carousel/lib/styles.css";
const responsive = {
  superLargeDesktop: {
    // the naming can be any, depends on you.
    breakpoint: { max: 4000, min: 3000 },
    items: 5
  },
  desktop: {
    breakpoint: { max: 3000, min: 1024 },
    items: 3
  },
  tablet: {
    breakpoint: { max: 1024, min: 464 },
    items: 2
  },
  mobile: {
    breakpoint: { max: 464, min: 0 },
    items: 1
  }
};


export default function Home() {

  const [reply,setReply] = useState('');
  const saveReply = async() =>{
    let res = await axios.post('https://630857e8722029d9ddcc981b.mockapi.io/forms', {
      reply: reply,
       
    })
    .then(function (response) {
      console.log('Stored successfully');
    })
  }
    // ...
    const [likes, setLikes] = React.useState(0);
  
    function handleClick() {
      setLikes(likes + 1);
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
      {/* Stack the columns on mobile by making one full-width and the other half-width */}
      <Row>
        <Col  md={8} xs={12}>
        <div className={styles.top}>
            <p>Baleno (2015-2022)</p><span>safety</span><hr></hr>
        </div>
           <div>
           <div><h6 classname="styles.h3">Q. How safe is Baleno Zeta on highways ? </h6>
               <div className={styles.ans1}><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
  <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
  <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
</svg>
            16.1k Views
        <span className={styles.line}>|</span>
        <div>
           <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">
               <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
            </svg>  Add Answer</div>
            
          </div>
          <hr></hr>
          <div>7 Answer</div>
          </div>
          <Row>
               <Col md={1} sm={2} xs={2}>
                  <h2 className={styles.anp}>R</h2>
               </Col>
               <Col md={11} sm={10} xs={10}>
                     <div>
                       <p><span className={styles.php}>Rohith </span> |3 Year ago </p>
                     </div>
            
                   <div className={styles.ans2}>
           
                       <div className={styles.ans3}>
                         <p>All varients of baleno comes with standard safety equipment like front dual airbags ebd abs etc..., if you search on internet there are some videos showing alott off damage on baleno in minor accident, this is because every manufacturer have different approch to provide safety, 
                               in maruti case they gave alot of crumple Zone to absorb any hits. If you open hood and see engine bay there is alot of space between radiator and enginr, in petrol its huge. This crumple Zone gets damaged in small accidents also but cost of repair is not high. My bumper got hit once(preety bad).Cost to replace it is 8k for entire piece. Compara...
                            <span>Read More</span>
                         </p>
                      </div>
                   </div>
                      
                   <div className={styles.ans31}>
                       
                         <div className={styles.ans61}>
                                    <div><button onClick={handleClick}><svg  xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                                    <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                                    </svg> </button> {likes} | Reply</div><svg xmlns="http://www.w3.org/2000/svg" width="10" height="16" fill="currentColor" class="bi bi-flag-fill" viewBox="0 0 16 16">
                                    <path d="M14.778.085A.5.5 0 0 1 15 .5V8a.5.5 0 0 1-.314.464L14.5 8l.186.464-.003.001-.006.003-.023.009a12.435 12.435 0 0 1-.397.15c-.264.095-.631.223-1.047.35-.816.252-1.879.523-2.71.523-.847 0-1.548-.28-2.158-.525l-.028-.01C7.68 8.71 7.14 8.5 6.5 8.5c-.7 0-1.638.23-2.437.477A19.626 19.626 0 0 0 3 9.342V15.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 1 0v.282c.226-.079.496-.17.79-.26C4.606.272 5.67 0 6.5 0c.84 0 1.524.277 2.121.519l.043.018C9.286.788 9.828 1 10.5 1c.7 0 1.638-.23 2.437-.477a19.587 19.587 0 0 0 1.349-.476l.019-.007.004-.002h.001"/>
                                    </svg>
                                    </div>
                    
                          </div>
                                    
                       
                                    <div>
                                     <Accordion defaultActiveKey="0">
                                                  <Accordion.Item eventKey="0">
                                                    <Accordion.Header>Reply</Accordion.Header>
                                                    <Accordion.Body>
                                                    <Form>
                                                    <Form.Group className="mb-3" controlId="formBasicEmail">
                                                        
                                                        <Form.Control type="text" as="textarea" onChange={(e)=>{setReply(e.target.value)}} row={15} placeholder="Have to say something.." />
                                                       
                                                      </Form.Group>
                                                   </Form>
                                                 <div className={styles.btn}> 
                                                   <span><Button variant="primary" type="submit">
                                                          Cancel
                                                   </Button>
                                                   </span>  
                                                   <Button variant="primary" type="submit" onClick={saveReply}>
                                                          Submit
                                                   </Button>
                                                </div>
                                                    </Accordion.Body>
                                                    
                                                      
                                                 </Accordion.Item>
                                      </Accordion>
                                  </div>
                                    
                            
               
            </Col>
            </Row>
            <Row>
               <Col md={1} sm={2} xs={2}>
                  <h2 className={styles.anp1}>A</h2>
               </Col>
               <Col md={11} sm={10} xs={10}>
                     <div>
                       <p><span className={styles.php}> Abbas</span> |3 Year ago </p>
                     </div>
                     <div className={styles.ans2}>
           
                       <div className={styles.ans3}>
                         <p> Its pretty safe..2 air bags are not enough thought! But ABS is initiative and driving dynamic (ride and handling) are very stable 
                          triple digit Speed is a breeze affair1 But still drive slow and safely! 
                          </p>
                        
                       </div>
                   </div>
                      
                   <div className={styles.ans6}>
                    
                                    <div><button onClick={handleClick}><svg  xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                                    <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                                    </svg> </button> {likes} | Reply</div><svg xmlns="http://www.w3.org/2000/svg" width="10" height="16" fill="currentColor" class="bi bi-flag-fill" viewBox="0 0 16 16">
                                    <path d="M14.778.085A.5.5 0 0 1 15 .5V8a.5.5 0 0 1-.314.464L14.5 8l.186.464-.003.001-.006.003-.023.009a12.435 12.435 0 0 1-.397.15c-.264.095-.631.223-1.047.35-.816.252-1.879.523-2.71.523-.847 0-1.548-.28-2.158-.525l-.028-.01C7.68 8.71 7.14 8.5 6.5 8.5c-.7 0-1.638.23-2.437.477A19.626 19.626 0 0 0 3 9.342V15.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 1 0v.282c.226-.079.496-.17.79-.26C4.606.272 5.67 0 6.5 0c.84 0 1.524.277 2.121.519l.043.018C9.286.788 9.828 1 10.5 1c.7 0 1.638-.23 2.437-.477a19.587 19.587 0 0 0 1.349-.476l.019-.007.004-.002h.001"/>
                                    </svg>
                    </div>
                    
                </Col>
            
            </Row>
            <Row>
               <Col md={1} sm={2} xs={2}>
                  <h2 className={styles.anp}>r</h2>
               </Col>
               <Col md={11} sm={10} xs={10}>
                     <div>
                       <p><span className={styles.php}> Jasan</span> |3 Year ago </p>
                     </div>
                     <div className={styles.ans2}>
           
                       <div className={styles.ans3}>
                         <p> very safe, even at highspeed car maintain its stability.ABS works well
                          </p>
                        
                       </div>
                       
                   </div>
                      
                   <div className={styles.ans6}>
                                    <div><svg  xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                                    <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                                    </svg> | Reply</div><svg xmlns="http://www.w3.org/2000/svg" width="10" height="16" fill="currentColor" class="bi bi-flag-fill" viewBox="0 0 16 16">
                                    <path d="M14.778.085A.5.5 0 0 1 15 .5V8a.5.5 0 0 1-.314.464L14.5 8l.186.464-.003.001-.006.003-.023.009a12.435 12.435 0 0 1-.397.15c-.264.095-.631.223-1.047.35-.816.252-1.879.523-2.71.523-.847 0-1.548-.28-2.158-.525l-.028-.01C7.68 8.71 7.14 8.5 6.5 8.5c-.7 0-1.638.23-2.437.477A19.626 19.626 0 0 0 3 9.342V15.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 1 0v.282c.226-.079.496-.17.79-.26C4.606.272 5.67 0 6.5 0c.84 0 1.524.277 2.121.519l.043.018C9.286.788 9.828 1 10.5 1c.7 0 1.638-.23 2.437-.477a19.587 19.587 0 0 0 1.349-.476l.019-.007.004-.002h.001"/>
                                    </svg>
                    </div>
                    <p className={styles.ans5}>View More Answers<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-compact-down" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1.553 6.776a.5.5 0 0 1 .67-.223L8 9.44l5.776-2.888a.5.5 0 1 1 .448.894l-6 3a.5.5 0 0 1-.448 0l-6-3a.5.5 0 0 1-.223-.67z"/>
                      </svg></p>
                  <div className={styles.sbmt}>
                      <Form>
                        <Form.Group className="mb-3" controlId="formBasicEmail">
                        
                           <Form.Label>Add your Answer</Form.Label>
                           <Form.Control type="text" as="textarea" row={10} placeholder="Have Something to say.." />
                          
                         </Form.Group>
                      </Form>
                      <Button variant="primary" type="submit">
                                     Submit Answer
                      </Button>
                  </div>
                  <div>
                    <div className={styles.scroll}>
                      <Carousel responsive={responsive}>
                        <div>
                            <div className={styles.scrollbx}>
                              <h5>
                                Q. What is difference between 2018 petrol Baleno...
                               </h5>
                                  <div className={styles.scrollbx1}>
                                    <span>P</span>
                                   <p>Asked by Himanshu 4 question </p>
                                   </div>
                             </div>
                            
                       </div>
                       
                       <div>
                       <div className={styles.scrollbx}>
                              <h5>
                                Q. Is thereany change in Maruti Baleno 2019 in inter...
                               </h5>
                                  <div className={styles.scrollbx1}>
                                    <span>R</span>
                                   <p>Asked by Rishu </p>
                                   </div>
                             </div>
                       </div>
                       <div>
                       <div className={styles.scrollbx}>
                              <h5>
                                Q. Are there going to be any changes to the steering...
                               </h5>
                                  <div className={styles.scrollbx1}>
                                    <span>P</span>
                                   <p>Asked by Raj 2 Answer </p>
                                   </div>
                             </div>
                        </div>
                        <div>
                        <div className={styles.scrollbx}>
                              <h5>
                                Q. Are there going to be any changes to the steeering...
                               </h5>
                                  <div className={styles.scrollbx1}>
                                    <span>P</span>
                                   <p>Asked by Raj 2 Answer </p>
                                   </div>
                             </div>
                        </div>
                       
                      </Carousel>
                    </div>
                  </div>
                    
                </Col>
            
            </Row>
          
          
           </div>

        
        </Col>
        <Col  md={4} xs={12}>
        <div className={styles.photo2}>
            <p>Trending Maruti Suzuki Cars</p><span>View All</span><hr></hr>
            
        </div>
        <div className={styles.photo}>
          <Row>
            <Col md={4} xs={4}>
              <img src="/brz.png"/>
            </Col>
            <Col md={8} xs={8}>
              <h6>BREZZA</h6>
              Rs. 7.99 Lakh
            </Col>
            <hr></hr>
          </Row>
          
          <Row>
            <Col md={4} xs={4}>
            <img src="/c2.png"/>
            </Col>
            <Col md={8} xs={8}>
            <h6>ERTIGA</h6>
              Rs. 8.55 Lakh
            </Col>
            <hr></hr>
          </Row>
          <Row>
            <Col md={4} xs={4}>
            <img src="/c3.png"/>
            </Col>
            <Col md={8} xs={8}>
            <h6>Baleno</h6>
              Rs. 6.42 Lakh
            </Col>
            <hr></hr>
          </Row>
          <Row>
            <Col md={4} xs={4}>
            <img src="/c4.png"/>
            
            </Col>
            
            <Col md={8} xs={8}>
            <h6>CELERIO</h6>
              Rs. 5.23 Lakh
            </Col>
            <hr></hr>
          </Row>
          <Row>
            <Col md={4} xs={4}>
            <img src="/c5.png"/>
            </Col>
            <Col md={8} xs={8}>
            <h6>Maruti DZIRE</h6>
              Rs. 6.23 Lakh
            </Col>
            <hr></hr>
          </Row>
          <Row>
            <Col md={4} xs={4}>
              <img src="/c6.png"/>
            </Col>
            <Col md={8} xs={8}>
              <h6>Alto K10</h6>
              Rs. 3.99 Lakh
            </Col>
            
          </Row>
         
          </div>
        </Col>
      </Row>

      
    </Container>

      <main className={styles.main}>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
