import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/dataget.module.css'
import axios from 'axios';
import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';
import 'bootstrap/dist/css/bootstrap.min.css';
import { useState } from 'react';


export default function Home() {
    const [name,setName] = useState('');
    
    const axios = require('axios').default;

// Make a request for a user with a given ID
axios.get('https://630857e8722029d9ddcc981b.mockapi.io/forms')
  .then(function (response) {
    // handle success
    console.log(response);
  })
  .catch(function (error) {
    // handle error
    console.log(error);
  })
  .then(function () {
    // always executed
  });
  axios.get('https://630857e8722029d9ddcc981b.mockapi.io/forms', {
    params: {
        name:priya
    }
  })
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  })
  .then(function () {
    // always executed
  });  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
                                     <div className={styles.form1}>
      
                                    <Form>
                                            <Form.Group className="mb-3">
                                            <Form.Label>Name</Form.Label>
                                            <Form.Control placeholder="write something"  />
                                        </Form.Group>
                                        <Form.Group className="mb-3">
                                        <Form.Label>Password</Form.Label>
                                            <Form.Control placeholder="write something"  />
                                        </Form.Group>
                                        <Form.Group className="mb-3">
                                        <Form.Label>Address</Form.Label>
                                            <Form.Control placeholder="write something"  />
                                        </Form.Group>
                                    </Form>
                                    </div>

      <main className={styles.main}>
        

        
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
