import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/forms.module.css'
import axios from 'axios';
import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';
import 'bootstrap/dist/css/bootstrap.min.css';
import { useState } from 'react';





export default function Home() {
  const [name,setName] = useState('');
  const [address,setAddress] =useState('')
  const [password,setpassword ] =useState('')


  const saveName = async() =>{
    let res = await axios.post('https://630857e8722029d9ddcc981b.mockapi.io/forms', {
      name: name,
      address: address,
      password: password 
    })
    .then(function (response) {
      console.log('Stored successfully');
    })
  }

  
  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.form1}>
      <Form>
      <Form.Group className="mb-3" controlId="formBasicEmail">
        <Form.Label>Name</Form.Label>
        <Form.Control type="name" placeholder="Enter name" onChange={(e)=>{setName(e.target.value)}}/>
        
      </Form.Group>
      

      <Form.Group className="mb-3" controlId="formBasicPassword">
        <Form.Label>Password</Form.Label>
        <Form.Control type="password" placeholder="Password"  onChange={(e)=>{setpassword(e.target.value)}} />
      </Form.Group>
      <Form.Group className="mb-3" controlId="formBasicEmail">
        <Form.Label> address</Form.Label>
        <Form.Control type="text" placeholder="Enter address" onChange={(e)=>{setAddress(e.target.value)}}/>
        </Form.Group>
      <Form.Group className="mb-3" controlId="formBasicCheckbox">
        <Form.Check type="checkbox" label="Check me out" />
      </Form.Group>
      
      <Button variant="primary" onClick={saveName}>
        Submit
      </Button>
    </Form>
    </div>
      <main className={styles.main}>
        
       </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
